# Sometimes parentheses are used for clarity.
Style/TernaryParentheses:
  Enabled: false


Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/AsciiComments:
  Exclude:
    - spec/

# [:one, :two] is fine
Style/SymbolArray:
  Enabled: false

# ['one', 'two'] is fine
Style/WordArray:
  Enabled: false

# @tiff: Sometimes (or might I argue, often) having the if conditional on
# its own line is better for readability,
Style/IfUnlessModifier:
  Enabled: false

# Note(kapil): Sometimes if !foo is preferable for legibility.
Style/NegatedIf:
  Enabled: false

# Disables `module_function` vs `extend self` checks
#  `module_function` doesn't support private methods
Style/ModuleFunction:
  Enabled: false

# [
#   commas,
#   to make diffs,
#   smaller,
# ]
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

# We cannot enforce nesting of modules/class because by default this would load
#   eg namespaces via `app/controllers` before it would load namespace in `app/models`
#   and hence not load the required `app/models` file
Style/ClassAndModuleChildren:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

# @cbuchan: Sometimes this is desired behavior and isn't just a style concern
Style/DoubleNegation:
  Enabled: false
